import time
from array import array


MODULUS = 1_000_000_007


def extendedGcd(a, b):
    x0, y0 = 1, 0
    x1, y1 = 0, 1
    while b:
        q = a // b
        a, b = b, a - q * b
        x0, x1 = x1, x0 - q * x1
        y0, y1 = y1, y0 - q * y1
    return a, x0, y0


def modularInverse(value, modulus):
    gcd, x, _ = extendedGcd(value, modulus)
    if gcd != 1:
        raise ValueError("inverse does not exist")
    return x % modulus


def nonnegativeGapStats(a, b, c):
    """Return count and sum of gaps in the semigroup generated by a, b, c."""
    bModA = b % a
    inverseB = modularInverse(bModA, a)
    cAsBSteps = (c % a) * inverseB % a
    inverseCSteps = modularInverse(cAsBSteps, a)

    prefixMinimums = array("Q", [0]) * a
    cStep = 0
    bTotal = 0
    currentMinimum = (1 << 63) - 1

    for t in range(a):
        value = cStep * c + bTotal
        if value < currentMinimum:
            currentMinimum = value
        prefixMinimums[t] = currentMinimum

        bTotal += b
        cStep -= inverseCSteps
        if cStep < 0:
            cStep += a

    suffixMinimum = 10**40
    bTimesA = b * a
    cStep = inverseCSteps
    bTotal = b * (a - 1)

    totalCount = 0
    totalSum = 0
    bResidueBase = 0
    residue = 0

    for residueBase in range(a):
        if residueBase > 0:
            value = cStep * c + bTotal - bTimesA
            if value < suffixMinimum:
                suffixMinimum = value

            bTotal -= b
            cStep += inverseCSteps
            if cStep >= a:
                cStep -= a

        prefixCutoff = a - residueBase - 1
        minimumOffset = prefixMinimums[prefixCutoff]
        if suffixMinimum < minimumOffset:
            minimumOffset = suffixMinimum

        firstReachable = bResidueBase + minimumOffset
        gapCount = firstReachable // a
        totalCount += gapCount
        totalSum += gapCount * residue + a * gapCount * (gapCount - 1) // 2

        bResidueBase += b
        residue += bModA
        if residue >= a:
            residue -= a

    return totalCount, totalSum


def unreachableSum(power):
    a = 17**power
    b = 19**power
    c = 23**power

    shift = a + b + c
    gapCount, gapSum = nonnegativeGapStats(a, b, c)

    belowShiftSum = shift * (shift - 1) // 2
    return (belowShiftSum + gapSum + gapCount * shift) % MODULUS


def runTests():
    assert unreachableSum(1) == 8_253
    assert unreachableSum(2) == 60_258_000


if __name__ == "__main__":
    runTests()
    start = time.time()
    answer = unreachableSum(6)
    elapsed = time.time() - start

    print("Found " + str(answer) + " in " + str(elapsed) + " seconds.")
